site_name: Leaf Area Index Documentation

repo_url: https://github.com/ETC-UA/LeafAreaIndex.jl

site_dir: 'docs/site'
markdown_extensions: [mathjax]
# the url needs to come before the custom .js script
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML','mathjaxhelper.js']

