site_name: Leaf Area Index Documentation
site_author: Ken Bastiaensen
repo_url: https://github.com/ETC-UA/LeafAreaIndex.jl
docs_dir: 'build'
site_dir: 'mkdocs_site'
theme: readthedocs

# python:
#    version: 2 # for unicode
#    setup_py_install: true

#the third-party extenison mdx_math.py comes with a setup.py script
# Thank you Dmitry Shachnev (https://github.com/mitya57/python-markdown-math) 
markdown_extensions:
    - extra
    - mdx_math: 
        enable_dollar_delimiter: True #for use of inline $..$
    - fenced_code
    - codehilite
    - footnotes

extra_css:
  - assets/Documenter.css

# Required to load the MathJax javascript for the mdx_math.py
extra_javascript: #['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML']
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    - assets/mathjaxhelper.js

pages:
# Needs an `index.md` file, otherwise readthedocs will fall back to README.md
    - LeafAreaIndex.jl: index.md
    - Quick Intro: quick_intro.md
    - Calibration: calibration.md
    - Gap Fraction: gapfraction.md
    - LAI Inversion: LAI.md
    - Clumping: clumping.md
